force sync

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -23,8 +23,12 @@ jobs:
       run: pip install -r requirements.txt
     - name: List directory contents for debugging
       run: |
-        echo "Listing directory contents:"
+        echo "Listing directory contents in root:"
         ls -R
+        echo "Listing directory contents in sensor_api:"
+        ls -R sensor_api
+        echo "Listing directory contents in sensor_api/tests:"
+        ls -R sensor_api/tests
     - name: Run unit tests
       run: |
         # Ensure the test file exists at the expected path
@@ -34,6 +38,17 @@ jobs:
           echo "Test file not found: sensor_api/tests/test_visit_sensor.py"
           exit 1
         fi
+    #     echo "Listing directory contents:"
+    #     ls -R
+    # - name: Run unit tests
+    #   run: |
+    #     # Ensure the test file exists at the expected path
+    #     if [ -f sensor_api/tests/test_visit_sensor.py ]; then
+    #       python sensor_api/tests/test_visit_sensor.py
+    #     else
+    #       echo "Test file not found: sensor_api/tests/test_visit_sensor.py"
+    #       exit 1
+    #     fi
       #   - name: Unit tests
       # run: python sensor_api/tests/test_visit_sensor.py #removed the -m unittest 
       # unittest sensor_api.tests.test_visit_sensor
